dataset: "LBY_2"

path:
  corpus_path: "/home/ubuntu/ChangNam/tts/LBY_2"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "./raw_data/AUDIOBOX_44k"
  preprocessed_path: "./FastSpeech2/preprocessed_data/AUDIOBOX_44k"

preprocessing:
  val_size: 463
  text:
    text_cleaners: ["korean_cleaners"]
    language: "ko"
  audio:
    sampling_rate: 44100
    max_wav_value: 32767.0
  stft:
    filter_length: 2048
    hop_length: 512
    win_length: 2048
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 16000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
